name: Checking Code Quality
on: ["push", "pull_request"] ## run on push and pulls
jobs:
  eslint:
    name: Run Code Quality Static Checks ## the name of our job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dev Dependencies
        run: npm install --only=dev
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
